﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace MLModelLaptopPrice_ConsoleApp1
{
    public partial class MLModelLaptopPrice
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"CPU", @"CPU"),new InputOutputColumnPair(@"GPU", @"GPU"),new InputOutputColumnPair(@"RAMType", @"RAMType"),new InputOutputColumnPair(@"SSD", @"SSD")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"GHz", @"GHz"),new InputOutputColumnPair(@"RAM", @"RAM"),new InputOutputColumnPair(@"Screen", @"Screen"),new InputOutputColumnPair(@"Storage", @"Storage"),new InputOutputColumnPair(@"Weight", @"Weight")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"CPU",@"GPU",@"RAMType",@"SSD",@"GHz",@"RAM",@"Screen",@"Storage",@"Weight"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=5,NumberOfIterations=30,MinimumExampleCountPerLeaf=27,LearningRate=0.999999776672986,LabelColumnName=@"Price",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.04036625307498,FeatureFraction=0.99999999,L1Regularization=2E-10,L2Regularization=0.0412740801234059},MaximumBinCountPerFeature=559}));

            return pipeline;
        }
    }
}
