
// This file was auto-generated by ML.NET Model Builder. 

using MLModelLaptopPrice_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModelLaptopPrice.ModelInput sampleData = new MLModelLaptopPrice.ModelInput()
{
    CPU = @"i5",
    GPU = @"intel",
    RAM = 4F,
    RAMType = @"ddr3",
    Storage = 500F,
    SSD = false,
    Weight = 2F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModelLaptopPrice.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");


Console.WriteLine($"CPU: {@"i5"}");
Console.WriteLine($"GPU: {@"intel"}");
Console.WriteLine($"RAM: {4F}");
Console.WriteLine($"RAMType: {@"ddr3"}");
Console.WriteLine($"Storage: {500F}");
Console.WriteLine($"SSD: {false}");
Console.WriteLine($"Weight: {2F}");
Console.WriteLine($"Price: {527F}");


Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

